@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Adquisicio
class AssolimentJoc
class CarteraUsuaris
class CatalegJocs
class EspecAssolimentJoc
enum EstatJoc << enumeration >>
enum EstatSessioJoc << enumeration >>
class Joc
class Preu
class Revisio
class SessioJoc
class Usuari
class node4 as "package  model.excepcions" << package >>

Adquisicio         "1" *-[#595959,plain]-> "joc\n1" Joc                
Adquisicio         "1" *-[#595959,plain]-> "preu\n1" Preu               
Adquisicio          -[#595959,dashed]->  Preu               : "«create»"
Adquisicio         "1" *-[#595959,plain]-> "revisio\n1" Revisio            
Adquisicio         "1" *-[#595959,plain]-> "sessionsJoc\n*" SessioJoc          
AssolimentJoc      "1" *-[#595959,plain]-> "especAssolimentJoc\n1" EspecAssolimentJoc 
CarteraUsuaris     "1" *-[#595959,plain]-> "usuaris\n*" Usuari             
CatalegJocs        "1" *-[#595959,plain]-> "jocs\n*" Joc                
Joc                "1" *-[#595959,plain]-> "especsAssoliment\n*" EspecAssolimentJoc 
Joc                "1" *-[#595959,plain]-> "estatJoc\n1" EstatJoc           
SessioJoc          "1" *-[#595959,plain]-> "assolimentsJoc\n*" AssolimentJoc      
SessioJoc          "1" *-[#595959,plain]-> "estatSessioJoc\n1" EstatSessioJoc     
Usuari             "1" *-[#595959,plain]-> "adquisicions\n*" Adquisicio         
@enduml
